branch-defaults:
  default:
    environment: Udacity-env
    group_suffix: null
deploy:
  artifact: ./archive.zip
global:
  application_name: Udacity
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
